package ventanas;

import SuperMercado.Almacen;
import SuperMercado.Producto;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Joe
 */
public class AdExterno extends javax.swing.JFrame {

     Administrador administrador ;
     public  Almacen market;
     Producto producto;
    /**
     * Creates new form AdExterno
     * @param market
     */
    public AdExterno(Almacen market) {
        this.market = market;
      
        initComponents();
        Manejadorventana mv = new Manejadorventana();
        MostrarVentana.addActionListener(mv);
        
        
              this.Acercade.addActionListener(new ActionListener() {

            @Override
            public void actionPerformed(ActionEvent e) {
                
                JOptionPane.showMessageDialog(AdExterno.this,"Programa creado por: Joseph Bejarano");
                }
        });

        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem2 = new javax.swing.JMenuItem();
        Desktop = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        Inicio = new javax.swing.JMenuItem();
        Cerrar = new javax.swing.JMenuItem();
        MostrarVentana = new javax.swing.JMenuItem();
        Help = new javax.swing.JMenu();
        Acercade = new javax.swing.JMenuItem();

        jMenuItem2.setText("jMenuItem2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout DesktopLayout = new javax.swing.GroupLayout(Desktop);
        Desktop.setLayout(DesktopLayout);
        DesktopLayout.setHorizontalGroup(
            DesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 700, Short.MAX_VALUE)
        );
        DesktopLayout.setVerticalGroup(
            DesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 340, Short.MAX_VALUE)
        );

        jMenuBar1.setBackground(new java.awt.Color(255, 255, 255));

        jMenu1.setText("File");

        Inicio.setText("Inicio");
        Inicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InicioActionPerformed(evt);
            }
        });
        jMenu1.add(Inicio);

        Cerrar.setText("Cerrar");
        jMenu1.add(Cerrar);

        MostrarVentana.setText("Mostrar venta");
        jMenu1.add(MostrarVentana);

        jMenuBar1.add(jMenu1);

        Help.setText("Help");

        Acercade.setText("Acerca de ");
        Help.add(Acercade);

        jMenuBar1.add(Help);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Desktop)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Desktop)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void InicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InicioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_InicioActionPerformed

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem Acercade;
    private javax.swing.JMenuItem Cerrar;
    private javax.swing.JDesktopPane Desktop;
    private javax.swing.JMenu Help;
    private javax.swing.JMenuItem Inicio;
    private javax.swing.JMenuItem MostrarVentana;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem2;
    // End of variables declaration//GEN-END:variables

    public class Manejadorventana implements ActionListener{
   
     
        @Override
        public void actionPerformed(ActionEvent ae) {
           if(administrador == null){
               administrador = new Administrador(market);
                 Desktop.add(administrador);
           }
           
         
           administrador.setVisible(true);
           
        }
        
    }

}
