/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventanas;


import SuperMercado.Almacen;
import SuperMercado.Compra;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.event.InternalFrameAdapter;
import javax.swing.event.InternalFrameEvent;
import javax.swing.table.AbstractTableModel;

/**
 *
 * @author Joe
 */
public class VentasRealizadas extends javax.swing.JInternalFrame {

    private Almacen market;
    private Compra compra;

    /**
     * Creates new form VentasRealizadas
     */
    public VentasRealizadas(Almacen market) {
         initComponents();
       this.market=market;
  
       this.addInternalFrameListener(new InternalFrameAdapter() {
            @Override
            public void internalFrameActivated(InternalFrameEvent e) {
                super.internalFrameActivated(e);
                jTable1.updateUI();
            }
        });
  
  
        this.jTable1.setModel(new AbstractTableModel() {

            @Override
            public int getRowCount() {
                if (market.getCompras() == null) {
                    return 0;
                } else {
                    return market.getCompras().size();

                }
            }

            @Override
            public int getColumnCount() {
           return 4;
            }

            @Override
            public String getColumnName(int ColumIndex) {
               switch(ColumIndex){
                   case 0:
                       return "Vendedor";
                   case 1:
                       return "Cliente";
                   case 2:
                       return "Costo";
                   case 3:
                       return "Puntos Otorgados";
                  
               }
               return "";
            }

            @Override
            public Object getValueAt(int RowIndex, int ColumIndex) {
                compra = market.getCompras().get(RowIndex);
              
                switch(ColumIndex){
                    case 0:
                        return compra.getEmpleado().getNombres();
                    case 1:
                        return compra.getCliente().getNombres();
                    case 2:
                        return compra.getCostoTotal();
                    case 3:
                        return compra.acomularPuntos()+"";
                }
           return "";
            }
        });

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 385, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables


}
